### ISSUE TITLE
the problem of noise precision 

### ISSUE THREAD

**Issue by zyy341** [takashi-takahashi/approximate_message_passing#1]
Hi,
in line 9 of the following algorithm，which stated in VAMP paper，to calculate the parameter $d_k$ ，the parameter $gamma_w$ is included.  According to the paper, the parameter $gamma_w$ represents noise precision.
![20190730101421](https://user-images.githubusercontent.com/37187361/62095407-f2445c80-b2b2-11e9-902f-83e3e8adf293.png)
In the [3]Self Averaging VAMP.ipynb, the noise variance is set to $1e^-2$. But when solving the svd vamp, the solver did not consider noise precision. 
![20190730103307](https://user-images.githubusercontent.com/37187361/62096227-7d265680-b2b5-11e9-9162-8f7d425ed0b5.png)

I want to know if the parameter noise precision $gamma_w$ is necessary?

Could you be so kind as to provide me with some help on the above-mentioned problem? Thank you for your kindness, and your prompt attention to this letter will be highly appreciated.

Sincerely,

Peicong Zheng

**Comment by takashi-takahashi** [comment]
Hi,

I'm sorry for my late reply. I haven't noticed this issue in the last two month.
(I hope you had already solved the problem.)


I answer the question in the following.

> I want to know if the parameter noise precision $gamma_w$ is necessary.

No, it's not necessary for LASSO.
This is because LASSO is obtained as a MAP estimate of the following posterior:
$p(x | y) \propto exp(-(y- Ax)^2 /2 ) exp(-\lambda |x|)$. 
In this case, the likelihood term doesn't contain noise precision.
(try to write down the VAMP algorithm for the above MAP estimation problem)
The situation is different from the Bayesian estimation.

Of course, you can include noise precision $\gamma_w$ in the likelihood term. (In this case, $p(x | y) \propto exp(-\gamma_w (y- Ax)^2 /2 ) exp(-\lambda |x|)$.)
However, as explained in the section I.A of the original VAMP paper (https://arxiv.org/abs/1610.03082), this is equivalent to the above MAP estimation with a regularization parameter $\lambda \gamma_w$.

Sincerely,
